# Generated by Django 5.2.12 on 2026-03-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
